- platform: rpi_gpio
  ports:
    23: Ativado
    22: Acionado
  invert_logic: true
- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('device_tracker.52008849ec808451', 'home')
           or is_state('device_tracker.iphonedeflavialan', 'home') }}
    portao_template:
      friendly_name: "Portão"
      device_class: opening
      value_template: "{{ is_state('binary_sensor.portao', 'on') }}"
      icon_template: >-
          {% if is_state('binary_sensor.portao', 'off') %}
            mdi:garage
          {% else %}
            mdi:garage-open
          {% endif %}
- platform: mqtt
  name: Portão
  state_topic: "tele/sonoff6075/SENSOR"
  device_class: opening
  payload_on: "ON"
  payload_off: "OFF"  
  value_template: '{{ value_json["Switch2"] }}'
- platform: ping
  name: tv_sala
  host: 192.168.86.165
  count: 5
  scan_interval: 30
- platform: ping
  name: tv_quarto
  host: 192.168.86.86
  count: 5
  scan_interval: 30
- platform: ping
  name: tv_isabelle
  host: 192.168.86.31
  count: 5
  scan_interval: 30
- platform: ffmpeg_motion
  name: camera_fundos
  changes: 10
  input: !secret input_camera_fundos
- platform: ffmpeg_motion
  name: camera_frente
  changes: 10
  input: !secret input_camera_frente
- platform: ffmpeg_motion
  name: camera_interna
  changes: 10
  input: !secret input_camera_interna