homeassistant:
  # Name of the location where Home Assistant is running
  name: FRIS
  # Location required to calculate the time the sun rises and sets
  latitude: -25.451756
  longitude: -49.343350
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 905
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml
  
  whitelist_external_dirs:
  - /config/tts
#  - /backup

frontend: !include frontend.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
# Show links to resources in log and frontend
# introduction:

# Enables configuration UI
config:

ios:

#cloud:
#  alexa:
#    filter:
#      include_domains:
#        - scripts
#        - light
#        - switch

panel_iframe: !include panel_iframe.yaml

#customizer:
#  custom_ui: local

http:
  # Secrets are defined in the file secrets.yaml
   api_password: !secret http_password
   base_url: !secret base_url
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem   
#   trusted_networks:
#     - 127.0.0.1
#     - 192.168.86.0/24
   
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

logger:
  default: warning
#  logs:
#    homeassistant.components.mqtt: debug
#    homeassistant.components.automation: debug

# Weather prediction
#sensor:
#  - platform: yr

weather: !include weather.yaml

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /config/tts
    time_memory: 600
#    language: 'pt-BR'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
#variable: !include variables.yaml
input_text: !include input_text.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
camera: !include camera.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
weblink: !include weblink.yaml
shell_command: !include shell_command.yaml

ifttt:
  key: !secret ifttt

telegram_bot:
  - platform: polling
    api_key: !secret api_key 
    allowed_chat_ids:
      - 328083280
      - -301349283

notify:
  - name: telegram_bot
    platform: telegram
    chat_id: 328083280
  - name: telegram_group
    platform: telegram
    chat_id: -301349283
    
ffmpeg:

python_script:

recorder:
  purge_keep_days: 5
  
zone:
  - name: home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 20
    icon: mdi:home-outline
  - name: BRF
    latitude: !secret brf_latitude
    longitude: !secret brf_longitude
    radius: 100
    icon: mdi:briefcase
  - name: home_arriving
    latitude: !secret home_arriving_latitude
    longitude: !secret home_arriving_longitude
    radius: 100
    icon: mdi:home-outline
  - name: home_arriving2
    latitude: !secret home_arriving2_latitude
    longitude: !secret home_arriving2_longitude
    radius: 100
    icon: mdi:home-outline
  - name: sogro
    latitude: !secret sogro_latitude
    longitude: !secret sogro_longitude
    radius: 100
  - name: escola
    latitude: !secret escola_latitude
    longitude: !secret escola_longitude
    radius: 100
    icon: mdi:school
  - name: pai
    latitude: !secret pai_latitude
    longitude: !secret pai_longitude
    radius: 100
    
#alexa:

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
#  agent_user_id: FRIS GA
#  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light

mqtt:

#image_processing:
#  - platform: openalpr_local
#    region: eu
#    source:
#    - entity_id: camera.teste_carro
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.frente
#      - entity_id: camera.interna
#  - platform: dlib_face_identify
#    source:
#      - entity_id: camera.frente
#      - entity_id: camera.interna
#    faces:
#      Robson: /config/Robson.jpg
#      Flavia: /config/Flavia.jpg
#  - platform: opencv
#    name: Garage Person
#    source:
#      - entity_id: camera.frente_local
#    classifier:
#      mom: /config/haarcascade_fullbody.xml
#  - platform: opencv
#    name: Garage Plate
#    source:
#       - entity_id: camera.frente_local
#    classifier:
#      mom: /config/haarcascade_licence_plate_rus_16stages.xml
vacuum:
  - platform: roomba
    name: FRITZ
    host: 192.168.86.38
    username: 3143C90C02131830
    password: :1:1507417757:sY0dqzT8bxdvS5SQ