homeassistant:
  # Name of the location where Home Assistant is running
  name: FRIS
  # Location required to calculate the time the sun rises and sets
  latitude: -25.451756
  longitude: -49.343350
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 905
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml
  
  whitelist_external_dirs:
  - /config/tts
#  - /backup

frontend: !include frontend.yaml

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  
# Show links to resources in log and frontend
# introduction:

# Enables configuration UI
config:

#ios:

#cloud:
#  alexa:
#    filter:
#      include_domains:
#        - scripts
#        - light
#        - switch

customizer:
  custom_ui: local

http:
  # Secrets are defined in the file secrets.yaml
   api_password: !secret http_password
   base_url: !secret base_url
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem   
#   trusted_networks:
#     - 127.0.0.1
#     - 192.168.86.0/24
   cors_allowed_origins:
   - https://reformedreality.com
   - http://reformedreality.com

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

logger:
  default: warning
#  logs:
#    homeassistant.core: debug
#    homeassistant.components.automation: debug

# Weather prediction
#sensor:
#  - platform: yr

weather: !include weather.yaml
tts: !include tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
#variable: !include variables.yaml
input_text: !include input_text.yaml
device_tracker: !include device_tracker.yaml
input_boolean: !include input_boolean.yaml
camera: !include camera.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
weblink: !include weblink.yaml
shell_command: !include shell_command.yaml
cover: !include cover.yaml
rest_command: !include rest_command.yaml
alarm_control_panel: !include alarm_control_panel.yaml
vacuum: !include vaccum.yaml
binary_sensor: !include binary_sensor.yaml
zone: !include zone.yaml
telegram_bot: !include telegram_bot.yaml
notify: !include notify.yaml
climate: !include climate.yaml

ifttt:
  key: !secret ifttt

ffmpeg:

python_script:

recorder:
  purge_keep_days: 5
    
#alexa:

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - switch
    - light
    - media_player
    - script
  entity_config:
    switch.luz_esquerda:
      name: Left Light
    switch.luz_direita:
      name: Right Light
    switch.luz_central:
      name: Central Light
    switch.power_tv_s:
      name: Room TV
    switch.power_tv_1:
      name: Bedroom TV
    switch.power_net_s:
      name: Room Setup box
    switch.mute_tv_s:
      name: Mute Room TV
    switch.cervejeira:
      name: Beer fridge
    script.tv_sala_globo:
      name: Room TV Globo
    script.tv_sala_sbt:
      name: Room TV SBT
    switch.portao:
      name: gate
mqtt:
  broker: 192.168.86.139
  
zoneminder:
  host: 192.168.86.174:8124
  username: admin
  password: !secret zm_password
  
panel_custom:
  - name: camera
    sidebar_title: Camera
    sidebar_icon: mdi:cctv
    url_path: camera
    config:
      title: Camera
#microsoft_face:
#  api_key: f58276501ad74262b5560217ecabfc89
#  azure_region: westcentralus
  
#image_processing:
#  - platform: openalpr_local
#    region: br
#    source:
#    - entity_id: camera.teste_carro
#  - platform: dlib_face_detect
#    source:
#      - entity_id: camera.frente
#      - entity_id: camera.interna
#  - platform: dlib_face_identify
#    source:
#      - entity_id: camera.frente
#      - entity_id: camera.interna
#    faces:
#      Robson: /config/Robson.jpg
#      Flavia: /config/Flavia.jpg
#  - platform: opencv
#    name: Garage Person
#    source:
#      - entity_id: camera.frente_local
#    classifier:
#      mom: /config/haarcascade_fullbody.xml
#  - platform: opencv 
#    name: Garage Plate
#    source:
#       - entity_id: camera.frente
#    classifier:
#      mom: /config/haarcascade_licence_plate_rus_16stages.xml