- platform: template
  covers:
    portao:
      friendly_name: "Portão"
      value_template: "{{ is_state('binary_sensor.portao','on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.portao','on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}
      open_cover:
        service: switch.toggle
        data:
          entity_id: switch.portao
      close_cover:
        service: switch.toggle
        data:
          entity_id: switch.portao
      stop_cover:
        service: switch.toggle
        data:
          entity_id: switch.portao