- platform: nmap_tracker
  hosts:
    - 192.168.86.102
    - 192.168.86.144
  consider_home: 900
- platform: gpslogger
  password: !secret gpslogger_password
#- platform: google_maps
#  username: robsonschmidt@gmail.com
#  password: !secret google_maps_password