- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  aliases:
    a3201c775e2fc7f4bac720b2fdee6974d0d08fab: 'Robson''s Echo Dot'
    0568d8d6a4f06465d3f1cc0921ce5f0f: 'Quarto'
    7f53f138d32720396167f6e706667479: 'Sala'
    d8853bdab4078fbd52b122fbd80c83e1: 'Churrasqueira'
    9655b4bbcd738dab6d6457a5ae80d56e105a64db: 'iPhone de Robson'
- platform: universal
  name: TV Quarto
  children:
  - media_player.quarto
  commands:
    turn_on:
      service: switch.turn_on
      entity_id: switch.power_tv_quarto
    turn_off:
      service: switch.turn_on
      entity_id: switch.power_tv_quarto
    volume_up:
      service: switch.turn_on
      entity_id: switch.vol_cima_tv_quarto
    volume_down:
      service: switch.turn_on
      entity_id: switch.vol_baixo_tv_quarto
    volume_mute:
      service: switch.turn_on
      entity_id: switch.mute_tv_quarto
  attributes:
    volume_level: input_number.vol_tv_quarto
    state: binary_sensor.tv_quarto
- platform: universal
  name: TV Sala
  children:
  - media_player.Sala
  commands:
    turn_on:
      service: switch.turn_on
      entity_id: switch.power_tv_sala
    turn_off:
      service: switch.turn_on
      entity_id: switch.power_tv_sala
    volume_up:
      service: switch.turn_on
      entity_id: switch.vol_cima_tv_sala
    volume_down:
      service: switch.turn_on
      entity_id: switch.vol_baixo_tv_sala
    volume_mute:
      service: switch.turn_on
      entity_id: switch.mute_tv_sala
  attributes:
    volume_level: input_number.vol_tv_sala
    state: binary_sensor.tv_sala