- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  aliases:
    a3201c775e2fc7f4bac720b2fdee6974d0d08fab: 'Robson''s Echo Dot'
    0568d8d6a4f06465d3f1cc0921ce5f0f: 'Quarto'
    7f53f138d32720396167f6e706667479: 'Sala'
    d8853bdab4078fbd52b122fbd80c83e1: 'Churrasqueira'
- platform: universal
  name: TV Quarto
  children:
  - media_player.quarto
  commands:
    turn_on:
      service: switch.toggle
      entity_id: switch.power_tv_quarto
    turn_off:
      service: switch.toggle
      entity_id: switch.power_tv_quarto
    volume_up:
      service: switch.toggle
      entity_id: switch.vol_cima_tv_quarto
    volume_down:
      service: switch.toggle
      entity_id: switch.vol_baixo_tv_quarto
    volume_mute:
      service: switch.toggle
      entity_id: switch.mute_tv_quarto
    volume_set:
      service: script.turn_on
      data_template:
        entity_id: script.set_vol_quarto
        variables:
          vol: '{{ volume_level * 100 | int }}'
  attributes:
    volume_level: input_number.vol_tv_quarto
    state: binary_sensor.tv_quarto
- platform: universal
  name: TV Sala
  children:
  - media_player.Sala
  commands:
    turn_on:
      service: switch.toggle
      entity_id: switch.power_tv_sala
    turn_off:
      service: switch.toggle
      entity_id: switch.power_tv_sala
    volume_up:
      service: switch.toggle
      entity_id: switch.vol_cima_tv_sala
    volume_down:
      service: switch.toggle
      entity_id: switch.vol_baixo_tv_sala
    volume_mute:
      service: switch.toggle
      entity_id: switch.mute_tv_sala
    volume_set:
      service: script.turn_on
      data_template:
        entity_id: script.set_vol_sala
        variables:
          vol: '{{ volume_level * 100 | int }}'
    select_source:
      service: script.turn_on
      data_template:
        entity_id: script.select_source_sala
        variables:
          source: '{{ source }}'
  attributes:
    volume_level: input_number.vol_tv_sala
    state: binary_sensor.tv_sala
    source_list: input_select.source_tv_sala | options
    source: input_select.source_tv_sala | state