- platform: speedtest
  minute:
     - 0
  monitored_conditions:
     - ping
     - download
     - upload
- platform: systemmonitor
  resources:
     - type: disk_use_percent
       arg: /
     - type: memory_use_percent
     - type: swap_use_percent
     - type: load_1m
     - type: load_15m
     - type: processor_use
     - type: last_boot
- platform: google_wifi
- platform: template
  sensors:
    luz_central_amps:
      value_template: '{{ states.light.luz_central.attributes["current"] | replace(" A", "") | float }}'
      unit_of_measurement: 'A'
    luz_central_watts:
      value_template: '{{ states.light.luz_central.attributes["current_consumption"] | replace(" W", "") | float * 0.001 }}'
      unit_of_measurement: 'kW'
    luz_central_kwy:
      value_template: '{{ states.light.luz_central.attributes["total_consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
    luz_central_volts:
      value_template: '{{ states.light.luz_central.attributes["voltage"] | replace(" V", "") | float }}'
      unit_of_measurement: 'V'
    luz_esquerda_amps:
      value_template: '{{ states.light.luz_esquerda.attributes["current"] | replace(" A", "") | float }}'
      unit_of_measurement: 'A'
    luz_esquerda_watts:
      value_template: '{{ states.light.luz_esquerda.attributes["current_consumption"] | replace(" W", "") | float * 0.001  }}'
      unit_of_measurement: 'kW'
    luz_esquerda_kwy:
      value_template: '{{ states.light.luz_esquerda.attributes["total_consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
    luz_esquerda_volts:
      value_template: '{{ states.light.luz_esquerda.attributes["voltage"] | replace(" V", "") | float }}'
      unit_of_measurement: 'V'
    luz_direita_amps:
      value_template: '{{ states.light.luz_direita.attributes["current"] | replace(" A", "") | float }}'
      unit_of_measurement: 'A'
    luz_direita_watts:
      value_template: '{{ states.light.luz_direita.attributes["current_consumption"] | replace(" W", "") | float * 0.001 }}'
      unit_of_measurement: 'kW'
    luz_direita_kwy:
      value_template: '{{ states.light.luz_direita.attributes["total_consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
    luz_direita_volts:
      value_template: '{{ states.light.luz_direita.attributes["voltage"] | replace(" V", "") | float }}'
      unit_of_measurement: 'V'
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'  
- platform: season
- platform: template
  sensors:
    now:
      friendly_name: "Agora"
      value_template: >
       ● {{ states.sensor.dark_sky_temperature.state|round(0)}}°C
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}

    forecast_0:
      friendly_name: "Hoje"
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}

    forecast_1:
      friendly_name: "Amanhã"
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_1.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_1.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}

    forecast_2:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_2.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_2.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}

    forecast_3:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_3.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_3.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}

    forecast_4:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_4.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_4.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}

    forecast_5:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_5.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_5.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}

    forecast_6:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_6.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_6.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}

    forecast_7:
      value_template: >
       ⇧ {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°C | ⇩ {{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°C | ☂ {{states.sensor.dark_sky_precip_probability_7.state|round(0)}}% | Hum. {{states.sensor.dark_sky_humidity_7.state|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

# Previsão de tempo 
- platform: darksky
  api_key: c96f80d478f6e3c254f3d7d1863f7241
  units: si
  lang: pt
  forecast:
   - 1
   - 2
   - 3
   - 4
   - 5
   - 6
   - 7
  monitored_conditions:
   - summary
   - precip_probability
   - wind_speed
   - cloud_cover
   - icon
   - temperature_min
   - temperature_max
   - daily_summary
   - humidity
   - temperature
   - hourly_summary
   - precip_intensity_max
   - precip_type

# Tradução Previsão de tempo
#- platform: rest
#  method: POST
#  name: dark_sky_summary_pt
#  resource: https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20180312T184049Z.25ec68dcb8cdd93c.e8313f4eb494259e59ca6a6efd1c03e42e81d8a6&lang=en-pt
#  payload: >
#    text={{ states.sensor.dark_sky_summary.state }}
#  value_template: '{{ value_json.text }}'
#  headers:
#    User-Agent: Home Assistant
#    Content-Type: application/x-www-form-urlencoded
- platform: command_line
  name: dark_sky_summary_pt
  command: curl --data \"key=trnsl.1.1.20180312T184049Z.25ec68dcb8cdd93c.e8313f4eb494259e59ca6a6efd1c03e42e81d8a6&lang=en-pt&text={{ states.sensor.dark_sky_summary.state }}\" https://translate.yandex.net/api/v1.5/tr.json/translate
  value_template: >
   {% for text in value_json.text %}
   {{text}}
   {% endfor %}
- platform: command_line
  name: dark_sky_daily_summary_pt
  command: curl --data \"key=trnsl.1.1.20180312T184049Z.25ec68dcb8cdd93c.e8313f4eb494259e59ca6a6efd1c03e42e81d8a6&lang=en-pt&text={{ states.sensor.dark_sky_daily_summary.state }}\" https://translate.yandex.net/api/v1.5/tr.json/translate
  value_template: >
   {% for text in value_json.text %}
   {{text}}
   {% endfor %}
- platform: command_line
  name: dark_sky_hourly_summary_pt
  command: curl --data \"key=trnsl.1.1.20180312T184049Z.25ec68dcb8cdd93c.e8313f4eb494259e59ca6a6efd1c03e42e81d8a6&lang=en-pt&text={{ states.sensor.dark_sky_hourly_summary.state }}\" https://translate.yandex.net/api/v1.5/tr.json/translate
  value_template: >
   {% for text in value_json.text %}
   {{text}}
   {% endfor %}
  
# Google Travel Time
- platform: google_travel_time
  name: 'Para pai'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: 'Alameda Júlia da Costa, 2350 - Bigorrilho, Curitiba - PR, 80730-070, Brasil'
- platform: google_travel_time
  name: 'Para escola Isabelle'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: 'R. Prof. Ulisses Vieira, 2809 - Santa Quiteria, Curitiba - PR, 80310-120'
- platform: google_travel_time
  name: 'Para Casa'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: 'R. Pedro Carlesso, 63 - Cidade Industrial, Curitiba - PR'
- platform: google_travel_time
  name: 'Para Sogro'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: 'BR-116, 15575 - Xaxim, Curitiba - PR'
- platform: google_travel_time
  name: 'Para BRF'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: 'Rodovia Curitiba - Ponta Grossa Br-277 km 97, 3001 - Orleans, Curitiba - PR, 81020-430'
- platform: google_travel_time
  name: 'Para Compromisso'
  api_key: !secret google_travel_api
  origin: device_tracker.52008849ec808451
  destination: sensor.end_compromisso
  
# Template com endereço do próximo compromisso
- platform: template
  sensors:
    end_compromisso:
        friendly_name: "Endereço Compromisso"
        unit_of_measurement: 'degrees'
        value_template: "{{ states.calendar.robson.attributes.location }}"
        
# Bitcoin
#- platform: bitcoin
#  display_options:
#    - exchangerate
    
# Cotação de moedas
- platform: openexchangerates
  api_key: !secret exchange_api_key
  quote: BRL
  
# Horário
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    
# Pi-hole - DNS & Ad Blocker
- platform: pi_hole

## Armario Robson

# Temperatura
- platform: mqtt
  name: "Armario Robson Temperatura"
  state_topic: "tele/sonoff2731/SENSOR"
  value_template: "{{ value_json.AM2301.Temperature }}"
  unit_of_measurement: "°C"
  scan_interval: 20
  force_update: true
# Humidade
- platform: mqtt
  name: "Armario Robson Humidade"
  state_topic: "tele/sonoff2731/SENSOR"
  value_template: "{{ value_json.AM2301.Humidity }}"
  unit_of_measurement: "%"
  scan_interval: 20
  force_update: true
# Versão
- platform: mqtt
  name: Versão Armario Robson
  state_topic: "stat/sonoff2731/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

## Armario Flavia

# Temperatura
- platform: mqtt
  name: "Armario Flavia Temperatura"
  state_topic: "tele/sonoff1549/SENSOR"
  value_template: "{{ value_json.AM2301.Temperature }}"
  unit_of_measurement: "°C"
  scan_interval: 20
  force_update: true
# Humidade
- platform: mqtt
  name: "Armario Flavia Humidade"
  state_topic: "tele/sonoff1549/SENSOR"
  value_template: "{{ value_json.AM2301.Humidity }}"
  unit_of_measurement: "%"
  scan_interval: 20
  force_update: true
# Versão
- platform: mqtt
  name: Versão Armario Flavua
  state_topic: "stat/sonoff1549/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

## Aquecedor Isabelle

# Temperatura
- platform: mqtt
  name: "Temperatura Quarto Isabelle"
  state_topic: "tele/sonoff3944/SENSOR"
  value_template: "{{ value_json.AM2301.Temperature }}"
  unit_of_measurement: "°C"
  scan_interval: 20
  force_update: true
# Humidade
- platform: mqtt
  name: "Humidade Quarto Isabelle"
  state_topic: "tele/sonoff3944/SENSOR"
  value_template: "{{ value_json.AM2301.Humidity }}"
  unit_of_measurement: "%"
  scan_interval: 20
  force_update: true
# Versão
- platform: mqtt
  name: Versão Aquecedor Isabelle
  state_topic: "stat/sonoff3944/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
  
## Cervejeira

# Temperatura
- platform: mqtt
  name: "Temperatura Cervejeira"
  state_topic: "tele/sonoff7880/SENSOR"
  value_template: "{{ value_json.DS18B20.Temperature }}"
  unit_of_measurement: "°C"
  scan_interval: 20
  force_update: true
# Versão
- platform: mqtt
  name: Versão Cervejeira
  state_topic: "stat/sonoff7880/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

# Versão Luz Quarto
- platform: mqtt
  name: Versão Luz Quarto
  state_topic: "stat/sonoff4569/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

# Versão Luz Painel Quarto
- platform: mqtt
  name: Versão Luz Painel Quarto
  state_topic: "stat/sonoff4777/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

# Versão Luz Sacada Frente
- platform: mqtt
  name: Versão Sonoff Luz Sacada Frente
  state_topic: "stat/sonoff2343/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"
  
# Versão Luz Corredor
- platform: mqtt
  name: Versão Luz Corredor
  state_topic: "stat/sonoff6590/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"

# IP Luz Corredor
- platform: mqtt
  name: IP Luz Corredor
  state_topic: "tele/sonoff4569/INFO2"
  value_template: "{{ value_json['IPAddress'] }}"

# Ultima versão Sonoff Tasmota
- platform: rest
  name: Ultima Versão Sonoff
  resource: https://api.github.com/repos/arendst/Sonoff-Tasmota/releases/latest
  value_template: '{{ value_json.tag_name }}'
  headers:
    Accept: application/vnd.github.v3+json
    Content-Type: application/json
    User-Agent: Home Assistant REST sensor 
  scan_interval: 60

# Uso espaço no dropbox
- platform: rest
  name: Dropbox espaço usado
  method: POST
  resource: https://api.dropboxapi.com/2/users/get_space_usage
  value_template: '{{ value_json.used }}'
  headers:
    Authorization: !secret dropbox_auth
  scan_interval: 600

# RF Reciever  
- platform: mqtt
  state_topic: "sensors/rf/receiver"
  name: "RF Receiver"
  
# Cotação Bitcoin
- platform: template
  sensors:
    btc:
      friendly_name: "Cotação Bitcoin"
      unit_of_measurement: USD
      icon_template: mdi:currency-btc
      value_template: >
       {{ (1 / states.sensor.exchange_rate_sensor.attributes.BTC | float) | round(2) }}

## Portao       
       
# Versão
- platform: mqtt
  name: Versão Portao
  state_topic: "stat/sonoff6075/STATUS2"
  value_template: "{{ value_json['StatusFWR'].Version }}"