- platform: tplink
  host: 192.168.86.27
  friendly_name: 'display'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: tplink
  host: 192.168.86.41
  friendly_name: 'garden_light'
  username: robsonschmidt@gmail.com
  password: 14253678
- platform: broadlink
  host: 192.168.68.43
  mac: '34:EA:34:B3:00:CB'
  friendly_name: 'Suite'
  type: rm_mini
  timeout: 60
  switches:
    liga_net:
      friendly_name: 'liga_net'
      command_on: 'JgBQAAABJ5AXMxYzFjMWDxYOFg8TEhU0ExETNhM3EzYVNBYPFjMWDxUPFjMWDxUPFTUWDhYPEhQQOBQQFTQWNBYQFDMWNBYzFgAE7QABKEYVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5AXMxYzFjMWDxYOFg8TEhU0ExETNhM3EzYVNBYPFjMWDxUPFjMWDxUPFTUWDhYPEhQQOBQQFTQWNBYQFDMWNBYzFgAE7QABKEYVAA0FAAAAAAAAAAA='
    liga_tv:
      friendly_name: 'liga_tv'
      command_on: 'JgBYAAsAA/sWAAjCAAEojxUQExIUEBQRExEUERQRExEUNRM2EzcVNBU0FjMWDxYzFjMWNBUPFBEUEBYPFg8VDxYPEhMUNBY0FjMWMxYzFTQTAAU6AAEmSBQADQU='
      command_off: 'JgBYAAsAA/sWAAjCAAEojxUQExIUEBQRExEUERQRExEUNRM2EzcVNBU0FjMWDxYzFjMWNBUPFBEUEBYPFg8VDxYPEhMUNBY0FjMWMxYzFTQTAAU6AAEmSBQADQU='
    tv_source:
      friendly_name: 'tv_source_ok'
      command_on: 'JgBcAAABJ4sZEBUQFhAVDxYQFRAWEBUREjYZMRU0FjMXMhY0GQ0UNRYPFjQaMBYzGTEVEBYQFRIUMxYPFhAVEhQPFTQTNxQ2EgACYwcAAtUAASdHFQAMSAABKEUVAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgBUAAkAAl4AASiMFhAWDhURFw4YDhQRFg8XDhgxGDIWMxU1FzIWMxcOFTUVNRYPGA0VEBgPFBEYMBcPFBEZMRcyFDUUNBY1FhAXMhcABTsAASdGGAANBQAAAAA='
    tv_vol:
      friendly_name: 'TV Vol'
      command_on: 'JgBUAAABJpITERQRExEVEBYPFg8VERQQFDQWMxM2EzYUNRM3FQ8WMxYPFjMWMxYPFjMWDxURExIUNRMSFQ8WNhUQFTMWNBU0FgAFNgABKEcWAAINDwANBQAAAAA='
      command_off: 'JgBQAAABJZITEhQQExIVDxYPFg8WDhYRFDMWMxYzEzcUNRcyFg8WMxYOFjQWDhYzFjQWDhUREhETNhQREzYTEhUPFjQWMxYzFgAFNgABKEcWAA0FAAAAAAAAAAA='
    net_canal:
      friendly_name: 'Net Canal'
      command_on: 'JgBQAAABKJAWMxYzFjMWDxYOFg8WEBczFg8VMxQ2EzYUNRQREzYTEhUPFhAVEBQREzQWEBUOEhQSNhQ1EzYVNRYOFjMWNBYzFgAE7QABKEYWAA0FAAAAAAAAAAA='
      command_off: 'JgBWAAkABtsLgQABJ48TNxQ1FjMTEhMRFRAWDhY0FBAWMxY0FTQWMxYPFjMWDhYPEjcXDhYzFjMWDxYOFg8WMxYPFjMWDhMSEzYUNRM3FQAE7QABKUYWAA0FAAA='
    tv_cima:
      friendly_name: 'tv_cima'
      command_on: 'JgBQAAABJ44VEBkMFhAZCxcPGQwWEBkMGDEWNBcyGTEZMBgxGQ0WMxkvFxAYMRYzGTEVEBkPFBAZDBU0GQ0YDRYPGTEVNBczGAAFOQABJ0cWAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ48WDxUREhMVEBMSFw8VERQQFjMTNhM3FDYSNxQ1FBITNhQ1Fg8YNBYQFRAWDxI3FBISExM2FBETMhs0EjYXEBU0FAAFPQABJkcXAA0FAAAAAAAAAAA='
#- platform: broadlink
#  host: 192.168.68.37
#  mac: '34:ea:34:b5:32:c5'
#  friendly_name: 'Sala'