- platform: tplink
  host: 192.168.86.27
  name: 'display'
  username: robsonschmidt@gmail.com
  password: !secret http_password
- platform: tplink
  host: 192.168.86.41
  name: 'garden_light'
  username: robsonschmidt@gmail.com
  password: !secret http_password
- platform: broadlink
  host: 192.168.86.43
  mac: '34:EA:34:B3:00:CB'
  name: 'Suite'
- platform: broadlink
  host: 192.168.86.37
  mac: '34:ea:34:b5:32:c5'
  name: 'Sala'
  switches:
    power_net_s:
      friendly_name: 'Power Net Sala'
      command_on: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
      command_off: 'JgBYAAABJpIUNxI3EzYTEhMRExMSExI2ExITNxI4ETcUNhMSEzcSExIREzcTExISEjcTERMTEhMSNhMSEzYTOBISEzYTNxM2EwAFBwABKUgTAAxcAAEnSBMADQU='
    power_tv_s:
      friendly_name: 'Power TV Sala'
      command_on: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJSSFTYRNxQ2FBETERQSExISExI2EzcUNRUQFBETEhMTEhITEhI3FBAUERQRExMTEhMREzcTEhI2FDYUNRQ2EzYUNhMABgGUkhQ1FDYTNxQRExMSExIRFBEUNhQ1FDYUERMSExISExISExEUNhQRExITEhMSEhITExI3ExISNxQ2ETgTNhM3EzcTAA0FAAAAAAAAAAAAAAAA'
    source_tv_s:
      friendly_name: 'Source TV Sala'
      command_on: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKSFDYTNxI4ERITERQRFBEUEBQ2EzYTNxIRExEUERMTEhETNhMRExIUERISEhMSEhIRExEUNhQ1FTUUNRU1EzYUNxIABgyTkhQ1FDYTNxMSEhEUEBQQFBETNhQ2FDYUERQQExEUERESEzYUERMSEhITEhMQFBAVEBMRFDYUORM3EzUTNxQ1EzcTAA0FAAAAAAAAAAAAAAAA'
    vol_up_tv_s:
      friendly_name: 'Vol Cima TV Sala'
      command_on: 'JgBGAJSSFDUUNRQ2FBITERMSExITERM3EzUUNRQSExITERMSExITNhM2EzcTEhMQFBITEhMRExITEhMREzYUNhM2EzcTNhMADQUAAA=='
      command_off: 'JgBGAJSSFDUUNRQ2FBITERMSExITERM3EzUUNRQSExITERMSExITNhM2EzcTEhMQFBITEhMRExITEhMREzYUNhM2EzcTNhMADQUAAA=='
    vol_down_tv_s:
      friendly_name: 'Vol Baixo TV Sala'
      command_on: 'JgCMAJKRFDYUNRM3ExITERIRFBETERM3E0ESNhUREhETEhQQExITNxI3ExEUNiIRExMSERQQExMTERI3ExISNhQ2EzcTNxIABgyTkhQ1FDYUNhMRExISExIRFBETNhQ1FDUUEBUQFBAVDxUREzUVNhMQFDYUEBQQFRAUEBMSExITNhISFDYTNhQ2EjcUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKRFDYUNRM3ExITERIRFBETERM3E0ESNhUREhETEhQQExITNxI3ExEUNiIRExMSERQQExMTERI3ExISNhQ2EzcTNxIABgyTkhQ1FDYUNhMRExISExIRFBETNhQ1FDUUEBUQFBAVDxUREzUVNhMQFDYUEBQQFRAUEBMSExITNhISFDYTNhQ2EjcUAA0FAAAAAAAAAAAAAAAA'
    ch_up_net_s:
      friendly_name: 'Canal Cima Net Sala'
      command_on: 'JgBYAAABJpIUNhM3FDYTExISEhITExI3EhMSNhM3EzcTNxISEzYTExISExISExIREzcTEhMSEhITNhM4EjcTNxIRFDYTNxM3EgAFCQABJ0kSAAxcAAEnSRIADQU='
      command_off: 'JgBYAAABJpIUNhM3FDYTExISEhITExI3EhMSNhM3EzcTNxISEzYTExISExISExIREzcTEhMSEhITNhM4EjcTNxIRFDYTNxM3EgAFCQABJ0kSAAxcAAEnSRIADQU='
    ch_down_net_s:
      friendly_name: 'Canal Baixo Net Sala'
      command_on: 'JgBYAAABKJMSNhM3EzYUEhITEhETEhM3ExEUNhQ1FDYTNxMSEjYUERMTEjcSEhM2FDYTExISEhITNhQREzgSEhIfEjYUNhQ1FAAFCAABJ0gUAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABKJMSNhM3EzYUEhITEhETEhM3ExEUNhQ1FDYTNxMSEjYUERMTEjcSEhM2FDYTExISEhITNhQREzgSEhIfEjYUNhQ1FAAFCAABJ0gUAAxaAAEoSBMADQU='
    up_tv_s:
      friendly_name: 'Cima TV Sala'
      command_on: 'JgCMAJKTEjcTNhQ2ExIUEBMSEhMSERM2EzYUNhQSERITEhMREhEUERMSExETEhISEzUUNhUPEzcUNRM3FDYTNxISEhITNhQABguTkhQ1FTUTNhYQEhISEhMSEhMRNhQ2EzgTERMSERITERMSEhMSEhISEhMSEhM1FTUTEhM3EjcSNxQ1FDYTEhISEzcSAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJKTEjcTNhQ2ExIUEBMSEhMSERM2EzYUNhQSERITEhMREhEUERMSExETEhISEzUUNhUPEzcUNRM3FDYTNxISEhITNhQABguTkhQ1FTUTNhYQEhISEhMSEhMRNhQ2EzgTERMSERITERMSEhMSEhISEhMSEhM1FTUTEhM3EjcSNxQ1FDYTEhISEzcSAA0FAAAAAAAAAAAAAAAA'
    down_tv_s:
      friendly_name: 'Baixo TV Sala'
      command_on: 'JgCMAJOSFDUVNRU1FBETEhIRFBETERM2FDYTNhQRExETERMSFBATNhQSExETERMSEjcUNhMRExMRNxM2FDYTNRUREhEUNhQABgqVkRU0EzcUNhMRExITERIRFBEUNRQ1FTUTEhMSExEUEBMSEjcTEhIRFBAUERM2FDYTEhMREzcTNhM3EzcSERQREzYTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSFDUVNRU1FBETEhIRFBETERM2FDYTNhQRExETERMSFBATNhQSExETERMSEjcUNhMRExMRNxM2FDYTNRUREhEUNhQABgqVkRU0EzcUNhMRExITERIRFBEUNRQ1FTUTEhMSExEUEBMSEjcTEhIRFBAUERM2FDYTEhMREzcTNhM3EzcSERQREzYTAA0FAAAAAAAAAAAAAAAA'
    right_tv_s:
      friendly_name: 'Direita TV Sala'
      command_on: 'JgDSAJORFDUVNRQ1FBITERISFBESEhM2EzcTNxMRExESExISEhETEhQ1FBETEhIREzgSNxISFDYSERM3EzcSOA8UFBAUNhMABgyUkhI3EjcTNhQRExMSERITEhISNhU2EjcTEhMREhEVEBMRFBETNxISExEUERI2FDYTERM4EhETNxM3EjcUERIREzcTAAYMkZMUNhQ1FTYTEhMSExESEhMREzYUNxI2FBETEhISEhMTERIRFjQTERMSExETNxM2FBISNhQSETYUNhQ1FBETEhM2EwANBQAAAAAAAA=='
      command_off: 'JgDSAJORFDUVNRQ1FBITERISFBESEhM2EzcTNxMRExESExISEhETEhQ1FBETEhIREzgSNxISFDYSERM3EzcSOA8UFBAUNhMABgyUkhI3EjcTNhQRExMSERITEhISNhU2EjcTEhMREhEVEBMRFBETNxISExEUERI2FDYTERM4EhETNxM3EjcUERIREzcTAAYMkZMUNhQ1FTYTEhMSExESEhMREzYUNxI2FBETEhISEhMTERIRFjQTERMSExETNxM2FBISNhQSETYUNhQ1FBETEhM2EwANBQAAAAAAAA=='
    left_tv_s:
      friendly_name: 'Esquerda TV Sala'
      command_on: 'JgCMAJOSEzYSNxU2EhEUERQSERETExI3EjcUNRMRFBITEhIRExISNhMSEzYUERMTETYTNxQQFBETNBUSEjgSNxIRGxMSNxMABguTkhM3FDYUNRQSERITEhISEhITNxM2FDcRERMTEhISExESEzYTExA4ExISExI3EjcTEhISEjcTEhI2FDYUEBMTEjcTAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSEzYSNxU2EhEUERQSERETExI3EjcUNRMRFBITEhIRExISNhMSEzYUERMTETYTNxQQFBETNBUSEjgSNxIRGxMSNxMABguTkhM3FDYUNRQSERITEhISEhITNxM2FDcRERMTEhISExESEzYTExA4ExISExI3EjcTEhISEjcTEhI2FDYUEBMTEjcTAA0FAAAAAAAAAAAAAAAA'
    ok_tv_s:
      friendly_name: 'OK TV Sala'
      command_on: 'JgCMAJOSEzUVNRQ1FRAUEBMSExISEhI3FDUUNxMREhEUERQQFBEUDxUREhIYNhQQFEAUNhMREzcTNhQ2ExESNxQQExEVNRQABgqVkhM2EzcTNhMRExISERMRFBETNxM2FDUVEBMSEhISExIRExIUEBQQE0AVERM2EzcTERM3EzYTNxMREjYVEBQQFDYUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJOSEzUVNRQ1FRAUEBMSExISEhI3FDUUNxMREhEUERQQFBEUDxUREhIYNhQQFEAUNhMREzcTNhQ2ExESNxQQExEVNRQABgqVkhM2EzcTNhMRExISERMRFBETNxM2FDUVEBMSEhISExIRExIUEBQQE0AVERM2EzcTERM3EzYTNxMREjYVEBQQFDYUAA0FAAAAAAAAAAAAAAAA'
    um_net_s:
      friendly_name: '1 Net Sala'
      command_on: 'JgBYAAABJ5IUORI3EjcTERQRExMSEhM2ExITNxI3FDUTNxMSEjgSEhM2ExITEhMSEhITEhISExETExI3EzcTNxI2EzcTNxQ2EgAFCAABKEkTAAxaAAEnShMADQU='
      command_off: 'JgBYAAABJ5IUORI3EjcTERQRExMSEhM2ExITNxI3FDUTNxMSEjgSEhM2ExITEhMSEhITEhISExETExI3EzcTNxI2EzcTNxQ2EgAFCAABKEkTAAxaAAEnShMADQU='      
    dois_net_s:
      friendly_name: '2 Net Sala'
      command_on: 'JgBYAAABJpIUNhQ1FDYUEBMTEhITEhA5ExEUNhM3EzcSNxMREzgSEhMSEjcTEhITEhITEhISExETOBESFDYTNhQ2EzgSNxI3EwAFCAABJ0kUAAxaAAEnSBQADQU='
      command_off: 'JgBYAAABJpIUNhQ1FDYUEBMTEhITEhA5ExEUNhM3EzcSNxMREzgSEhMSEjcTEhITEhITEhISExETOBESFDYTNhQ2EzgSNxI3EwAFCAABJ0kUAAxaAAEnSBQADQU='
    tres_net_s:
      friendly_name: '3 Net Sala'
      command_on: 'JgBYAAABJpMTNxM2EzcSEhMSEhMSEhM2ExEUNhM4EjcSOBIRFDYTExI3EjgSEhISFRMSEhITEhITEhISEzYTNxM2EzgSNxM2EwAFCAABKEgUAAxaAAEnSRQADQU='
      command_off: 'JgBYAAABJpMTNxM2EzcSEhMSEhMSEhM2ExEUNhM4EjcSOBIRFDYTExI3EjgSEhISFRMSEhITEhITEhISEzYTNxM2EzgSNxM2EwAFCAABKEgUAAxaAAEnSRQADQU='      
    quatro_net_s:
      friendly_name: '4 Net Sala'
      command_on: 'JgBYAAABKJIUNRQ2EzcTEhITEhEUERM4EhISNxM2EzcTNxMSEjgTEBMSExITNhMTEhETEhMSExISOBI2ExITNxM3EjgSNhQ2FAAFBwABJ0kTAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABKJIUNRQ2EzcTEhITEhEUERM4EhISNxM2EzcTNxMSEjgTEBMSExITNhMTEhETEhMSExISOBI2ExITNxM3EjgSNhQ2FAAFBwABJ0kTAAxaAAEoSBMADQU='      
    cinco_net_s:
      friendly_name: '5 Net Sala'
      command_on: 'JgBYAAABJpEUNxI4EjYUERMRFBISExI3EhMSNxM3EjcTNhMTEjcSEhM2FBETOBISExISEhMRExMSEhM3EhITNhU4EzYSNxM2FAAFCAABJ0gUAAxaAAEoSBMADQU='
      command_off: 'JgBYAAABJpEUNxI4EjYUERMRFBISExI3EhMSNxM3EjcTNhMTEjcSEhM2FBETOBISExISEhMRExMSEhM3EhITNhU4EzYSNxM2FAAFCAABJ0gUAAxaAAEoSBMADQU='
    seis_net_s:
      friendly_name: '6 Net Sala'
      command_on: 'JgBYAAABKJIUNRM4EzYTEhISExISExI2FBETNxM2EzcTNxUSEjcTFBISEzcTNxISExETEhMSExISNxMSEhITNhQ2EzcUNhI3EwAFCAABJ0kTAAxaAAEoRxQADQU='
      command_off: 'JgBYAAABKJIUNRM4EzYTEhISExISExI2FBETNxM2EzcTNxUSEjcTFBISEzcTNxISExETEhMSExISNxMSEhITNhQ2EzcUNhI3EwAFCAABJ0kTAAxaAAEoRxQADQU='  
    sete_net_s:
      friendly_name: '7 Net Sala'
      command_on: 'JgBYAAABJ5IUNhM3EjgPFBMSExMSEhI4EhEUNhM3EzcSOBIREzcTEhM3EjgSNhMSExISExISExETExISExISNxM2EzgTNhI4DwAFCwABKEkSAAxbAAEoSRIADQU='
      command_off: 'JgBYAAABJ5IUNhM3EjgPFBMSExMSEhI4EhEUNhM3EzcSOBIREzcTEhM3EjgSNhMSExISExISExETExISExISNxM2EzgTNhI4DwAFCwABKEkSAAxbAAEoSRIADQU='  
    oito_net_s:
      friendly_name: '8 Net Sala'
      command_on: 'JgBYAAABKJIUNhI3EzYTExISExISEhM2ExMSNxM3EjYUNhMTEjcSExIRFBETEhM3EhMSERQRExITNxM3EjcTEhI3EzYTOBI3EgAFCAABKEkTAAxbAAEqSBIADQU='
      command_off: 'JgBYAAABKJIUNhI3EzYTExISExISEhM2ExMSNxM3EjYUNhMTEjcSExIRFBETEhM3EhMSERQRExITNxM3EjcTEhI3EzYTOBI3EgAFCAABKEkTAAxbAAEqSBIADQU='
    nove_net_s:
      friendly_name: '9 Net Sala'
      command_on: 'JgBYAAABKJMSNhQ5EjgSERMSExITEhI4EhETNxM3EjgSNhQREzcUEBM3ExITEhI4EhETEhMSExISEw85EzcTEhM3EjgSNxI3FAAFCAABJkkTAAxcAAEmSRMADQU='
      command_off: 'JgBYAAABKJMSNhQ5EjgSERMSExITEhI4EhETNxM3EjgSNhQREzcUEBM3ExITEhI4EhETEhMSExISEw85EzcTEhM3EjgSNxI3FAAFCAABJkkTAAxcAAEmSRMADQU='
    zero_net_s:
      friendly_name: '0 Net Sala'
      command_on: 'JgBYAAABJpMTNhM3EjcUEBMSExMSEhI3ExETOBM2EzcSNxMSEjcTEhMSEhITEhISExEUEhITEhIPOhM2FDYUNhM3EzcSNxI3EwAFCAABJ0kUAAxZAAEoSBMADQU='
      command_off: 'JgBYAAABJpMTNhM3EjcUEBMSExMSEhI3ExETOBM2EzcSNxMSEjcTEhMSEhITEhISExEUEhITEhIPOhM2FDYUNhM3EzcSNxI3EwAFCAABJ0kUAAxZAAEoSBMADQU='
    mute_tv_s:
      friendly_name: 'Mute TV Sala'
      command_on: 'JgCMAJORFTUUNhM2ExITERIRFBETEhM2FDUUNhUQEhISERUQFBAUNRU1EzcTNxMRExITERMRFBESEhISFBETNhM3EjYVNhMABguTkxU1FDUVNRQRFBAUERMRFBETNRM4EzYTERQRExEPFBUQEzYVNRM2FDYUERISFBETERMRExITERMQFTYTNhQ2EzYUAA0FAAAAAAAAAAAAAAAA'
      command_off: 'JgCMAJORFTUUNhM2ExITERIRFBETEhM2FDUUNhUQEhISERUQFBAUNRU1EzcTNxMRExITERMRFBESEhISFBETNhM3EjYVNhMABguTkxU1FDUVNRQRFBAUERMRFBETNRM4EzYTERQRExEPFBUQEzYVNRM2FDYUERISFBETERMRExITERMQFTYTNhQ2EzYUAA0FAAAAAAAAAAAAAAAA'
    gate:
      friendly_name: 'Portao'
      command_on: 'qgCCAxESHxIgIhERIBIgESATHxIfEx8jECISIhAiEREgIxAjECIRIhAiESIQEiAiERohEiAiEREgIhEAAXoRIhEUIBIgIhERIBEgEiASIBEgEiAiESIQIhAjEBIgIhEiESMQIxAiESIQEiAiEBMfEiAiEBIgIhAAAXsQIxATIBEgIxERIBIgESATIBEgEh8jECIQIxAiERIgIhAjESIRIhAjECIQEiAiERIgESEhERIfIxAAAXsQIhEUIBIgIhERIBIgESASIBIgESAiESIRIREiEREgIxAiEiIQIhEiESIQEiAiEREgEiAiEBIgIhEAAXsQIhASIBIfJBASIBIfEiASIBIfEiAiECMQIhEiEBIgIhEiESIQJREiECMQEh8jEBIgEiAiEBIgIhAAAXsQIxAVIBIfIxASHxIgEiASIBEgEh8jECIRIhEiEBIfIxEjECIRIhEiECIQEx8jEBIgESAiERIgIhAAAXsQIxATIBEgIhERIBIgESASIBIgEh8iESIQIxAiERIgIhAjESITIhAjECIQEiAiERIgESAiEREgIhEAAXsRIhITHxIgIhATHxIfEx8SIBIgESAjECIRIhAiERIfIxAjESIRIhAiESIRESAiERIgESAiERIfIxAAAXsRIxASIBEgIhESHxIfEx8THxIfEx8jECIRIhAiERIgIhAiEiIRIhAiESIRESAjEBIgESAiERIfIxAAAXsRIhMSIBEgIhERIREgEiASHxIgESEhESIRIhAjEBIfIxEjECIRIhAjECMQESAjEBIgEiAiEBIgIhAAAXsRIxASIBEgIhESHxIgEh8TIBEgEiAiECMQIhAjEBIfJBAjECMQIhEiECIREiAiEBIgEiAiEBIgIhAAAXsRIhAVIBIfIxASHxMfEiASIBEgEiAiECMQIhEiEBIgIxAjECMQIhEiECMQEiAiEBIgEiAiEBIgIxAAAXsRIhERIBIgIhERIBIgESASIBIfEiAjECIQIxAiEREgIxAiESMQIxAiECMQEiAiERIfEiAiEREhIREAAXsQIxAVHxIgIhATIBEgEiARIREgEh8jECIRIhAjEBIgIhEjECIRIhEiECIREh8jEBIgEiAiEBIgIhAAAXwRIhASIBIgIhASIBEgEiASIBIfEiAiESIQIhEiEREgIxAjESIQIxAiESIRESAjDxMfEx8jEBIgIhAABdwF3AAAAAA='
      command_off: 'qgCCAxESHxIgIhERIBIgESATHxIfEx8jECISIhAiEREgIxAjECIRIhAiESIQEiAiERohEiAiEREgIhEAAXoRIhEUIBIgIhERIBEgEiASIBEgEiAiESIQIhAjEBIgIhEiESMQIxAiESIQEiAiEBMfEiAiEBIgIhAAAXsQIxATIBEgIxERIBIgESATIBEgEh8jECIQIxAiERIgIhAjESIRIhAjECIQEiAiERIgESEhERIfIxAAAXsQIhEUIBIgIhERIBIgESASIBIgESAiESIRIREiEREgIxAiEiIQIhEiESIQEiAiEREgEiAiEBIgIhEAAXsQIhASIBIfJBASIBIfEiASIBIfEiAiECMQIhEiEBIgIhEiESIQJREiECMQEh8jEBIgEiAiEBIgIhAAAXsQIxAVIBIfIxASHxIgEiASIBEgEh8jECIRIhEiEBIfIxEjECIRIhEiECIQEx8jEBIgESAiERIgIhAAAXsQIxATIBEgIhERIBIgESASIBIgEh8iESIQIxAiERIgIhAjESITIhAjECIQEiAiERIgESAiEREgIhEAAXsRIhITHxIgIhATHxIfEx8SIBIgESAjECIRIhAiERIfIxAjESIRIhAiESIRESAiERIgESAiERIfIxAAAXsRIxASIBEgIhESHxIfEx8THxIfEx8jECIRIhAiERIgIhAiEiIRIhAiESIRESAjEBIgESAiERIfIxAAAXsRIhMSIBEgIhERIREgEiASHxIgESEhESIRIhAjEBIfIxEjECIRIhAjECMQESAjEBIgEiAiEBIgIhAAAXsRIxASIBEgIhESHxIgEh8TIBEgEiAiECMQIhAjEBIfJBAjECMQIhEiECIREiAiEBIgEiAiEBIgIhAAAXsRIhAVIBIfIxASHxMfEiASIBEgEiAiECMQIhEiEBIgIxAjECMQIhEiECMQEiAiEBIgEiAiEBIgIxAAAXsRIhERIBIgIhERIBIgESASIBIfEiAjECIQIxAiEREgIxAiESMQIxAiECMQEiAiERIfEiAiEREhIREAAXsQIxAVHxIgIhATIBEgEiARIREgEh8jECIRIhAjEBIgIhEjECIRIhEiECIREh8jEBIgEiAiEBIgIhAAAXwRIhASIBIgIhASIBEgEiASIBIfEiAiESIQIhEiEREgIxAjESIQIxAiESIRESAjDxMfEx8jEBIgIhAABdwF3AAAAAA='
    chromecast_s:
      friendly_name: 'Source Chromecast Sala'
      command_on: 'JgBGAJKVETkRORE5ERQQFRAVERQQFRE5ETkROREUERQRFBEUERQRORAVERUPOxAVDzsQOhA6EBUQOhA6EBUQOhAVEBUPFhAADQUAAA=='
      command_off: 'JgBGAJKVETkRORE5ERQQFRAVERQQFRE5ETkROREUERQRFBEUERQRORAVERUPOxAVDzsQOhA6EBUQOhA6EBUQOhAVEBUPFhAADQUAAA=='
    net_s:
      friendly_name: 'Source Net Sala'
      command_on: 'JgBGAJOUETkRORA6ERQQFRAVERQRFBA6ETkROhAVDxYQFQ8WEBUQFQ87EDoRORA6DzsQFRA6DzsPFhAVDxYQFRAVEDoQFRAADQUAAA=='
      command_off: 'JgBGAJOUETkRORA6ERQQFRAVERQRFBA6ETkROhAVDxYQFQ8WEBUQFQ87EDoRORA6DzsQFRA6DzsPFhAVDxYQFRAVEDoQFRAADQUAAA=='
    dvd_s:
      friendly_name: 'Source DVD Sala'
      command_on: 'JgBGAJOUEDoRORE5ERQRFRAUERQRFBE5EDsQOhAVEBUPFg8WDxYPFhA6EBUPFg8WEBUROQ87EDoQFQ87EDoQOhA6EBUPFhAADQUAAA=='
      command_off: 'JgBGAJOUEDoRORE5ERQRFRAUERQRFBE5EDsQOhAVEBUPFg8WDxYPFhA6EBUPFg8WEBUROQ87EDoQFQ87EDoQOhA6EBUPFhAADQUAAA=='
    power_dvd_s:
      friendly_name: 'Power DVD Sala'
      command_on: 'JgCgAJOVEBAQERAREBEQERAyDxIPEg8REBEQERAREBEQERARDxEQlBExEDIPMw8REBEQERAREBEQERARDxIPEg8yEDIQMhAyDzMPMhAyEDIQAAdblJQQEQ8SDxIPERAREDIQERAREBEPEg8SDxIPERAREBEQEQ+VEDEQMhAyEBEPEg8SDxEQERAREBEQERAREDIPMhAyEDIQMg8zDzIQMhAADQUAAAAAAAAAAA=='
      command_off: 'JgCgAJOVEBAQERAREBEQERAyDxIPEg8REBEQERAREBEQERARDxEQlBExEDIPMw8REBEQERAREBEQERARDxIPEg8yEDIQMhAyDzMPMhAyEDIQAAdblJQQEQ8SDxIPERAREDIQERAREBEPEg8SDxIPERAREBEQEQ+VEDEQMhAyEBEPEg8SDxEQERAREBEQERAREDIPMhAyEDIQMg8zDzIQMhAADQUAAAAAAAAAAA=='
    sair_net_s:
      friendly_name: 'Sair Net Sala'
      command_on: 'JgBgAAABJZQSOBE4EjgRFBETERQRFBE4ERQROBE5ETgSOBEUETgRFBETEjgRFBE4ERQRExITERQROBEUETgSExE5ETgRORE4EQAFCwABJUoSAAxdAAElSxEADF0AASVLEQANBQAAAAAAAAAA'
      command_off: 'JgBgAAABJZQSOBE4EjgRFBETERQRFBE4ERQROBE5ETgSOBEUETgRFBETEjgRFBE4ERQRExITERQROBEUETgSExE5ETgRORE4EQAFCwABJUoSAAxdAAElSxEADF0AASVLEQANBQAAAAAAAAAA'
    luz_sacada_frente:
      friendly_name: 'Luz Sacada Frente'
      command_on: 'qhQ0AAocChsKGwobChsKGxsLGgsKGwobChwKGxoMGgsLGxoLCxsLGxoLGgsKGwobGgsKGwoAAQEAAAAA'
      command_off: 'qhQ0AAocChsKGwobChsKGxsLGgsKGwobChwKGxoMGgsLGxoLCxsLGxoLGgsKGwobGgsKGwoAAQEAAAAA'
    luz_quarto:
      friendly_name: 'Luz Quarto'
      command_on: 'sgw0AA0kDSQNJCQNDSQNJA0kDSQNJA0kDSQNJCQNDSQkDQ0kDSQkDSQNDSQNJA0kDSQNJAwAAW8AAAAA'
      command_off: 'sgw0AA0kDSQNJCQNDSQNJA0kDSQNJA0kDSQNJCQNDSQkDQ0kDSQkDSQNDSQNJA0kDSQNJAwAAW8AAAAA'
    luz_painel_quarto:
      friendly_name: 'Luz Painel Quarto'
      command_on: 'sgw0AA0kJA0kDQ0kDSQkDQ0kJA0kDSQNJA0NJA0kDSQNJCQNJA0NJCQNJA0NJCQNJA0NJAwAAW8AAAAA'
      command_off: 'sgw0AA0kJA0kDQ0kDSQkDQ0kJA0kDSQNJA0NJA0kDSQNJCQNJA0NJCQNJA0NJCQNJA0NJAwAAW8AAAAA'
